### ISSUE TITLE
MQTT Support? 

### ISSUE THREAD

**Issue by briantho** [mikelawrence/aiosenseme#12]
Hi again, I was wondering if it's possible to add mqtt support to this project. I'm essentially looking for a way to have my mqtt broker talk to aiosenseme then talk to my fans. I use mcsMQTT as my broker via homeseer. It's a great little plugin to support mqtt for homeseer. I primarly use homeseer, because there are older plugins that i use that have never made there way to homeasssitant/OpenHAB. ANyway, I'd love to see this project support mqtt. If you could do this I would appreciate it a lot. Thanks

**Comment by bdraco** [comment]
MQTT support is beyond the scope of this project.  

You could use this library in-conjunction with https://pypi.org/project/asyncio-mqtt/
