### ISSUE TITLE
Additional Sensor Data

### ISSUE THREAD

**Issue by bepsoccer** [mikelawrence/aiosenseme#20]
Is it possible to consume the temp and humidity sensor values with is library?

**Comment by mikelawrence** [comment]
There doesn't appear to be any temp or humidity data in the packets that come from the fan. Previous debugging and associated discussions left us with the belief that temp and humidity is only used internal to the fan.

**Comment by bdraco** [comment]
If there is a way to see in the app, can you send a screenshot ?

**Comment by bdraco** [comment]
I couldn't find one. If you do, please reopen this issue
