### ISSUE TITLE
Haiku says Alexa can access fan speed 0-100

### ISSUE THREAD

**Issue by jkmaxwell** [mikelawrence/aiosenseme#24]
Hi folks, thanks for this amazing repo & package. This isn't really a bug but it's an issue.

Haiku sent me this in my response to asking for a fan speed lower than their "lowest" setting:

> The only way that is possible is for Alexa Integration. Our stock speeds are 1-7, Alexa can do a full 1%-100% incremental adjustments. 

So I'm wondering if there is a way for us to do this with aiosenseme, or if that is a proprietary alexa-only API. I've tried sending 1% through homeassistant but it quantizes it to "14" -> 1

https://bigassfans.com/alexa/
![image](https://user-images.githubusercontent.com/342903/151646828-ae60593d-b9ff-4e42-a008-5676d85884e0.png)

**Comment by bdraco** [comment]
The 7 speeds work out to something roughly like this:

1-14
15-28
29-43
...

**Comment by bdraco** [comment]
The device's internal api only has 7 speeds.

I don't think the device actually supports 100 speeds. The alexa may just hide the abstraction from you.

**Comment by jkmaxwell** [comment]
@bdraco I originally was going to argue with you. Then I just attached an Alexa, set it to 1%, and can verify haiku tech support is wrong and you are right 😀

**Comment by bdraco** [comment]
Good to know.  It doesn't seem like there is anything we can do about it though.

**Comment by jkmaxwell** [comment]
I just verified it works how you say @bdraco and that haiku is wrong. Thanks for pushing back on this!
