### ISSUE TITLE
Firmware 3.0.0 breaks Haikus

### ISSUE THREAD

**Issue by SuddenlyEngineer** [mikelawrence/aiosenseme#25]
See https://github.com/mikelawrence/senseme-hacs/issues/43 in the Home Assistant integration. Per BAF support, the (currently optional) firmware upgrade for the Haikus will use the i6 BAF app to communicate. I have not upgraded my fans, but they are currently planning for a forced upgrade in the fall. BAF have confirmed that the RTI and Control4 integrations will break with this change, and it appears this library will also be impacted.

**Comment by bdraco** [comment]
This issue is being tracked here https://github.com/home-assistant/core/issues/69370 along with downgrade instructions
