### ISSUE TITLE
Nice.

### ISSUE THREAD

**Issue by TomFaulkner** [mikelawrence/aiosenseme#4]
I just came across this today. I like what you've done with it. The response handling was something I wasn't happy with, but I wasn't really using the library anymore so I didn't bother with it and unfortunately I haven't really kept up with maintaining my library. I'm glad to see this in an aio library.

**Comment by mikelawrence** [comment]
I though about posting about this library in your repository but I've always thought it was in poor taste to tout a forked library in the original. Glad you approve.
